// This file was auto-generated by prisma-generator-typescript-interfaces

export interface Note {
  id: number;
  title: string;
  content: string | null;
  color: string | null;
  createdAt: Date;
  updatedAt: Date;
}
